- name: Installing
  user: Ansible
  hosts: web
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present
      register: nginx_installation

    - name: Starting server
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
      register: nginx_enabled

      when: nginx_installation is succeeded

    - name: Enabling server
      ansible.builtin.service:
        name: enable nginx
      when: nginx_enabled is succeeded
 

    - name: service ansible_facts
      ansible.builtin.service_facts:
      

    - name: checking whether the service started or not
      when: ansible_facts.services["nginx.service"].state=="running"
      ansible.builtin.debug:
        msg: "Server started and enabled successfully"
      
