- name: Installing
  user: Ansible
  hosts: web
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present
      register: nginx_installation

    - name: Starting server
      ansible.builtin.service:
        name: nginx
        state: started
      when: nginx_installation is failed

    - name: service ansible_facts
      ansible.builtin.service_facts:

    - name: checking whether the service started or not
      ansible.builtin.debug:
        msg: "nginx status is {{ nginx_status.stdout }}"
        when: ansible_facts.services["nginx.service"].state=="running"

