- name: While condition
  hosts: local
  vars:
    Number: 5
  tasks:
    - name: checking if number is greater than 4
      ansible.builtin.debug:
        msg: "number is greater than 4
      when: Number > 4
