- name: shell and cmd
  hosts: web
  connection: local
  tasks:
    - name: cmd output
      ansible.builtin.command:
        cmd: touch /home/ec2-user/file.txt

    - name: Shell output writing into file
      ansible.builtin.shell:
        cmd: echo "Hello and hi" >> /home/ec2-user/file.txt
      register: files

    - name: checking whether the write is successfull or not
      ansible.builtin.debug:
        msg: "The output is: {{files.rc}}"
      when: files.rc == 0

    - name: Shell grep
      ansible.builtin.shell:
        cmd: cat /home/ec2-user/file.txt
      register: output

    - name: output of file
      ansible.builtin.debug:
        msg: "The content in file.txt {{output}}"
      when: output.rc == 0